language: __sardonyx__

jobs:
  include:
    - name: __sardonyx__dev
      language: __sardonyx__
      group: dev
    - name: __sardonyx__
      language: __sardonyx__
      group: edge
    - name: __sardonyx__stable
      language: __sardonyx__
      group: stable
    - name: __opal__
      language: __opal__
      group: edge
    - name: __opal__stable
      language: __opal__
      group: stable
    - name: __stevonnie__
      language: __stevonnie__
      group: edge
    - name: __stevonnie__stable
      language: __stevonnie__
      group: stable
    - name: __sardonyx__stable_java
      language: java
      #group: stable

script:
- uname -a
- cat /etc/os-release
- ruby -v
- python -V
- ls -ahl /home/travis/*
